### ISSUE TITLE
Map View

### ISSUE THREAD

**Issue by Prymaldark** [raiguard/Factorio-Tapeline#3]
Tapeline will not work for me in the remote/map view. Would this functionality be simple enough to add in?

Steps to reproduce:
1. Be using Tapeline.
2. Look anywhere via the Map.
3. Try to measure in this map view.

**Comment by raiguard** [comment]
Unfortunately, you can't throw capsules in the map view. So being able to drag to create tapelines in the map view will be impossible. This is a base game limitation that I can't do anything about.

I plan on adding a selection tool that you will be able to use in the map view, but it won't draw the tape as you drag - you will select an area first, then it'll draw a tape. It won't be ideal, but it will be better than nothing.

**Comment by raiguard** [comment]
Drumroll please......................

I MAY HAVE SOLVED IT!

Turns out you can set a place_result on a selection tool. This has all of the desired qualifications:
- A way to detect the position while dragging by placing entities
- A way to detect when a drag finishes (the selection tool will provide its area)
- A way to detect if the player is holding shift
- A way to work on the map view (!)

The mod will have to be almost completely rewritten from scratch again, but it'll be worth it. Hurrah!

![image](https://user-images.githubusercontent.com/3515394/99586890-90c36800-29a5-11eb-9221-ef8bf9361245.png)

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/100314708-7a547800-2f74-11eb-9625-2417c41f448e.png)

Implemented for v2.0.0!

**Comment by raiguard** [comment]
v2.0.0 is out now!
