### ISSUE TITLE
Tape appears under walls and machines

### ISSUE THREAD

**Issue by Nevrai** [raiguard/Factorio-Tapeline#37]
### Description

The initial tape tile appears above the wall, but as you drag the tape, it appears _below_ the walls. In previous versions, in pre-Factorio 2.0, the tape would appear over walls, which is what I would expect. The tape appearing below most entities makes it hard or impossible to see it.

The tape also, unexpectedly, appears below machines, such as roboports – in fact, below every machine entity I’ve tested. The tape also appears below entities such as trees and rocks. The tape does, however, appear atop belts (as expected)!

https://github.com/user-attachments/assets/e41be94b-39da-4479-acc1-3eaf6a38856f

![image](https://github.com/user-attachments/assets/f640cc5c-8c73-4129-a51c-56601cdf2535)

### Versions
* **Factorio**: 2.0.23 (build 80769 expansion, win64)
* **Tapeline**: 3.0.0
* **Factorio Library**: 0.16.0

### Reproduction

Drag the tape over walls or machines.

**Comment by raiguard** [comment]
The actual bug is that the first square was drawing above the walls. If you want to tape to appear above walls you need to disable `Draw on ground` in the mod settings.

I can't make it draw above walls but below under entities; the only control I have is marking it as "draw on ground" or "don't draw on ground".
